name: se330_project1
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0 # Use the latest version from pub.dev
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/678.jpg
    - assets/images/123.jpg
    - assets/images/124.jpg
    - assets/images/235.jpg
    - assets/images/345.jpg
    - assets/images/457.jpg
    - assets/images/567.jpg
    - assets/images/234.jpg
    - assets/images/901.jpg
    - assets/images/679.jpg
    - assets/images/346.jpg
    - assets/images/568.jpg
    - assets/images/890.jpg
    - assets/images/234.jpg
    - assets/images/891.jpg
    - assets/images/901.jpg
    - assets/images/1012.jpg
